// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { Stimulus } from '../libs/stimulus'


import ChoicesController from './choices_controller'
Stimulus.register('choices', ChoicesController)

import HelloController from './hello_controller'
Stimulus.register('hello', HelloController)