// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { Stimulus } from '../libs/stimulus'


import ApexchartsController from './apexcharts_controller'
Stimulus.register('apexcharts', ApexchartsController)

import ChoicesController from './choices_controller'
Stimulus.register('choices', ChoicesController)

import ClientTypeController from './client-type_controller'
Stimulus.register('client-type', ClientTypeController)

import DatepickerController from './datepicker_controller'
Stimulus.register('datepicker', DatepickerController)

import EstimateController from './estimate_controller'
Stimulus.register('estimate', EstimateController)

import FilepondController from './filepond_controller'
Stimulus.register('filepond', FilepondController)

import HelloController from './hello_controller'
Stimulus.register('hello', HelloController)

import InvoiceController from './invoice_controller'
Stimulus.register('invoice', InvoiceController)

import LineItemController from './line-item_controller'
Stimulus.register('line-item', LineItemController)

import MenuController from './menu_controller'
Stimulus.register('menu', MenuController)

import Milkdown__Controllers__LinkController from './milkdown/controllers/link_controller'
Stimulus.register('milkdown--controllers--link', Milkdown__Controllers__LinkController)

import Milkdown__Controllers__SlashController from './milkdown/controllers/slash_controller'
Stimulus.register('milkdown--controllers--slash', Milkdown__Controllers__SlashController)

import Milkdown__Controllers__ToolbarController from './milkdown/controllers/toolbar_controller'
Stimulus.register('milkdown--controllers--toolbar', Milkdown__Controllers__ToolbarController)

import Milkdown__Controllers__TooltipController from './milkdown/controllers/tooltip_controller'
Stimulus.register('milkdown--controllers--tooltip', Milkdown__Controllers__TooltipController)

import MilkdownController from './milkdown_controller'
Stimulus.register('milkdown', MilkdownController)

import ResetFormController from './reset-form_controller'
Stimulus.register('reset-form', ResetFormController)

import SearchController from './search_controller'
Stimulus.register('search', SearchController)

import ToastController from './toast_controller'
Stimulus.register('toast', ToastController)